### ISSUE TITLE
download full free book

### ISSUE THREAD

**Issue by 0xh3LL0** [CeIest/BW-preview-DLer#3]
bw not only offer free preview but sometimes free the whole books
those books are free to read even without an account,
like this one `https://bookwalker.jp/dea6786ba7-181e-498b-af04-66d7f6d2a060/`
when i tried your tools it only download first 30 pages, while you can read the whole 500 pages in browser.

**Comment by CeIest** [comment]
That's because even though the books are free and doesn't require to log-in, the files are hosted under a different domain ("trial" books are under `viewer-trial.bookwalker.jp`, while the free "complete" books are under `viewer.bookwalker.jp`).
I took a quick look and unfortunately noticed the data interchange isn't the same for both systems :/
You made me curious so I'll try to see what I can do about those free whole books.

**Comment by CeIest** [comment]
Update: the method used for those kind of free books is the same for paid books, and I have yet to understand how their WEB displaying works (so that means it works with session IDs and scrambled images).
Sorry, but I'm unable help this time ):
I recommend looking into [this extension](https://github.com/ag0609/Project-BNDL); from what I've seen it manages to grab and decrypt native images

**Comment by 0xh3LL0** [comment]
i see

thank you for reply

**Comment by 0xh3LL0** [comment]
i'll take a look the extension

**Comment by 0xh3LL0** [comment]
it works, thank you for recommend!
